import { Conversation } from '@/lib/interface/message';

export const dataConversations: Conversation[] = [
	{
		id: '1',
		participants: ['1', '2'],
		unreadCount: 0,
		title: 'Leo',
		lastMessage: {
			id: '1',
			content: 'Hello, how are you?',
			senderId: '1',
			receiverId: '2',
			timestamp: new Date(),
			isRead: false,
			type: 'text',
		},
	},
	{
		id: '2',
		participants: ['1', '3'],
		unreadCount: 0,
		title: 'John',
		lastMessage: {
			id: '2',
			content: 'Hello, how are you?',
			senderId: '1',
			receiverId: '3',
			timestamp: new Date(),
			isRead: false,
			type: 'text',
		},
	},
	{
		id: '3',
		participants: ['1', '4'],
		unreadCount: 0,
		title: 'Jane',
		lastMessage: {
			id: '3',
			content: 'Hello, how are you?',
			senderId: '1',
			receiverId: '4',
			timestamp: new Date(),
			isRead: false,
			type: 'text',
		},
	},
	{
		id: '4',
		participants: ['1', '5'],
		unreadCount: 0,
		title: 'Jim',
		lastMessage: {
			id: '4',
			content: 'Hello, how are you?',
			senderId: '1',
			receiverId: '5',
			timestamp: new Date(),
			isRead: false,
			type: 'text',
		},
	},
	{
		id: '5',
		participants: ['1', '6'],
		unreadCount: 0,
		title: 'Jill',
		lastMessage: {
			id: '5',
			content: 'Hello, how are you?',
			senderId: '1',
			receiverId: '6',
			timestamp: new Date(),
			isRead: false,
			type: 'text',
		},
	},
];
